name: Profile Stats

on:
  create:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 7

      - uses: anmol098/waka-readme-stats@984399484754c41f271ddbd8b3799b98ad472497
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SYMBOL_VERSION: 1

      - run: |
          for i in {1..20}; do
            echo "Run #$i"
            curl "https://camo.githubusercontent.com/a1ec832c17e6a7638c03e360ff5a4a8b12cdb8b0f962be7590227cbb42f8480e/68747470733a2f2f6b6f6d617265762e636f6d2f67687076632f3f757365726e616d653d766965746e643936266c6162656c3d47697448756225323050726f66696c65253230566965777326636f6c6f723d306537356236267374796c653d666c6174"
            sleep 1
          done
